/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NwcSideDrawer {
    'close': () => Promise<void>;
    'open': () => Promise<void>;
    'opened': boolean;
    'titletext': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNwcSideDrawerElement extends Components.NwcSideDrawer, HTMLStencilElement {}
  var HTMLNwcSideDrawerElement: {
    prototype: HTMLNwcSideDrawerElement;
    new (): HTMLNwcSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'nwc-side-drawer': HTMLNwcSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NwcSideDrawer {
    'opened'?: boolean;
    'titletext'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'nwc-side-drawer': NwcSideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'nwc-side-drawer': LocalJSX.NwcSideDrawer & JSXBase.HTMLAttributes<HTMLNwcSideDrawerElement>;
    }
  }
}


