/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Task,
} from './components/todo-list/todo-list';

export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NwcSideDrawer {
    'close': () => Promise<void>;
    'open': () => Promise<void>;
    'opened': boolean;
    'titletext': string;
  }
  interface NwcSpinner {
    'color': string;
  }
  interface NwcStockFinder {}
  interface NwcStockPrice {
    'symbol': string;
  }
  interface NwcTodoList {
    'namespace': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNwcSideDrawerElement extends Components.NwcSideDrawer, HTMLStencilElement {}
  var HTMLNwcSideDrawerElement: {
    prototype: HTMLNwcSideDrawerElement;
    new (): HTMLNwcSideDrawerElement;
  };

  interface HTMLNwcSpinnerElement extends Components.NwcSpinner, HTMLStencilElement {}
  var HTMLNwcSpinnerElement: {
    prototype: HTMLNwcSpinnerElement;
    new (): HTMLNwcSpinnerElement;
  };

  interface HTMLNwcStockFinderElement extends Components.NwcStockFinder, HTMLStencilElement {}
  var HTMLNwcStockFinderElement: {
    prototype: HTMLNwcStockFinderElement;
    new (): HTMLNwcStockFinderElement;
  };

  interface HTMLNwcStockPriceElement extends Components.NwcStockPrice, HTMLStencilElement {}
  var HTMLNwcStockPriceElement: {
    prototype: HTMLNwcStockPriceElement;
    new (): HTMLNwcStockPriceElement;
  };

  interface HTMLNwcTodoListElement extends Components.NwcTodoList, HTMLStencilElement {}
  var HTMLNwcTodoListElement: {
    prototype: HTMLNwcTodoListElement;
    new (): HTMLNwcTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'nwc-side-drawer': HTMLNwcSideDrawerElement;
    'nwc-spinner': HTMLNwcSpinnerElement;
    'nwc-stock-finder': HTMLNwcStockFinderElement;
    'nwc-stock-price': HTMLNwcStockPriceElement;
    'nwc-todo-list': HTMLNwcTodoListElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NwcSideDrawer {
    'opened'?: boolean;
    'titletext'?: string;
  }
  interface NwcSpinner {
    'color'?: string;
  }
  interface NwcStockFinder {
    'onNwc_symbol_selected'?: (event: CustomEvent<string>) => void;
  }
  interface NwcStockPrice {
    'symbol'?: string;
  }
  interface NwcTodoList {
    'namespace'?: string;
    'onNwc_todo_list_update'?: (event: CustomEvent<Task[]>) => void;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'nwc-side-drawer': NwcSideDrawer;
    'nwc-spinner': NwcSpinner;
    'nwc-stock-finder': NwcStockFinder;
    'nwc-stock-price': NwcStockPrice;
    'nwc-todo-list': NwcTodoList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'nwc-side-drawer': LocalJSX.NwcSideDrawer & JSXBase.HTMLAttributes<HTMLNwcSideDrawerElement>;
      'nwc-spinner': LocalJSX.NwcSpinner & JSXBase.HTMLAttributes<HTMLNwcSpinnerElement>;
      'nwc-stock-finder': LocalJSX.NwcStockFinder & JSXBase.HTMLAttributes<HTMLNwcStockFinderElement>;
      'nwc-stock-price': LocalJSX.NwcStockPrice & JSXBase.HTMLAttributes<HTMLNwcStockPriceElement>;
      'nwc-todo-list': LocalJSX.NwcTodoList & JSXBase.HTMLAttributes<HTMLNwcTodoListElement>;
    }
  }
}


